books/urls.py
from django.urls import path, include
from .views import book_list, book_detail, chapter_detail, exercise_detail

app_name = 'books'

urlpatterns = [
    path('', book_list, name='book-list'),
    path('<slug:slug>/', book_detail, name='book-detail'),
    path('<book_slug>/<int:chapter_number>/', chapter_detail, name='chapter-detail'),
    path('<book_slug>/<int:chapter_number>/<int:exercise_number>/', exercise_detail, name='exercise-detail'),
]

digital_marketplace/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('books.urls', namespace='books'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/models.py
from django.conf import settings
from django.db import models
from django.db.models.signals import post_save
from django.shortcuts import redirect, reverse

class UserLibrary(models.Model):
    books = models.ManyToManyField('Book')
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    def book_list(self):
        return self.books.all()
    class Meta:
        verbose_name = 'User Library'
        verbose_name_plural = 'User Library'
    
def post_user_signup_receiver(sender, instance, created, *args, **kwargs):
    if created:
        UserLibrary.objects.get_or_create(user=instance)

post_save.connect(post_user_signup_receiver, sender=settings.AUTH_USER_MODEL)

class Author(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    slug = models.SlugField()

    def __str__(self):
        return f"{self.first_name} {self.last_name}"
    
class Book(models.Model):
    authors = models.ManyToManyField(Author)
    title = models.CharField(max_length=100)
    publication_date = models.DateTimeField()
    isbn = models.CharField(max_length=16)
    slug = models.SlugField()
    cover = models.ImageField()
    price = models.FloatField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("books:book-detail", kwargs={"slug": self.slug})
    

class Chapter(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    chapter_number = models.IntegerField()
    title = models.CharField(max_length=100)
    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("books:chapter-detail", kwargs={
            "book_slug": self.book.slug,
            'chapter_number': self.chapter_number
        })
    

class Exercise(models.Model):
    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE)
    exercise_number = models.IntegerField()
    page_number = models.IntegerField()
    title = models.CharField(max_length=100)
    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("books:exercise-detail", kwargs={
            "book_slug": self.chapter.book.slug,
            'chapter_number': self.chapter.chapter_number,
            'exercise_number': self.exercise_number
        })

class Solution(models.Model):
    exercise = models.ForeignKey(Exercise, on_delete=models.CASCADE)
    solution_number = models.IntegerField()
    image = models.ImageField()

    def __str__(self):
        return f"{self.exercise.title}-{self.pk}"
    

shopping_cart/models.py
from django.conf import settings
from django.db import models
from books.models import Book

class OrderItem(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)

    def __str__(self):
        return self.book.title
    

class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    is_ordered = models.BooleanField(default=False)
    items = models.ManyToManyField(OrderItem)
    reference_code = models.CharField(max_length=50)

    def __str__(self):
        return self.user.username
    
class Payment(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    total_amount = models.FloatField()
    data_paid = models.DateTimeField(auto_now_add=True)
    stripe_charge_id = models.CharField(max_length=100)

    def __str__(self):
        return self.stripe_charge_id
    

books/views.py
from django.http import Http404
from django.shortcuts import render, get_object_or_404

from .models import Book, Chapter, Exercise


def book_list(request):
    ''' Display a list of the books '''
    queryset = Book.objects.all()
    context = {
        'queryset': queryset
    }
    return render(request, "book_list.html", context)

def book_detail(request, slug):
    ''' Display a list of the chapters in this book '''
    book = get_object_or_404(Book, slug=slug)
    context = {
        'book': book
    }
    return render(request, 'book_detail.html', context)

def chapter_detail(request, book_slug, chapter_number):
    chapter_qs = Chapter.objects.filter(book__slug=book_slug).filter(chapter_number=chapter_number)
    if chapter_qs.exists():
        context = {
            'chapter': chapter_qs[0]
        }
        return render(request, 'chapter_detail.html', context)
    return Http404

def exercise_detail(request, book_slug, chapter_number, exercise_number):
    exercise_qs = Exercise.objects.filter(chapter__book__slug=book_slug).filter(chapter__chapter_number=chapter_number).filter(exercise_number=exercise_number)
    if exercise_qs.exists():
        context = {
            'exercise': exercise_qs[0]
        }
        return render(request, 'exercise_detail.html', context)
    return Http404

shopping_cart/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Digital Marketplace</title>

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>

<body>
    
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4 p-4 justify-content-between">
        <a class="navbar-brand" href="#">{% if request.user.is_authenticated %}Hello, {{ request.user.username }}!{% endif %}</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'books:book-list' %}">Home</a>
                </li>
                {% if request.user.is_authenticated %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'account_login' %}">Login</a>
                </li>
                {% endif %}
            </ul>
            <form class="form-inline mt-2 mt-md-0" style="position: absolute; right: 5px;">
                <input class="form-group mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                <button class="form-group btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>


      <div class='container'> 
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb bg-light px-3 py-3">
                {% block breadcrumb %}

                {% endblock breadcrumb %}
            </ol>
        </nav>

        {% block content %}
        {% endblock content %}

    </div>

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
    </script>
</body>

</html>

templates/book_detail.html
{% extends 'base.html' %}

{% block breadcrumb %}
    <li class="breadcrumb-item" aria-current="page"><a href="{% url 'books:book-list' %}">Book List</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{ book.title }}</li>
{% endblock breadcrumb %}


{% block content %}
    <div class='row'>
        <main class='col-md-3 mx-auto'>
            <div class="card" style="width: 20rem;">
                <div class="card-header text-center">{{ book.title }}</div>
                <img src="{{ book.cover.url }}" class="card-img-top" alt="...">
                <div class="card-body">
                  <p class="card-text">Published: {{ book.publication_date }}</p>
                </div>
            </div>
        </main>

        <aside class='col-md-4 mx-auto'>
            <div class="card" style="width: 18rem;">
                <div class="card-header">
                  Chapters
                </div>
                <ul class="list-group list-group-flush">
                    {% for chapter in book.chapter_set.all %}
                        <li class="list-group-item">{{ chapter.chapter_number }}. <a href="{{ chapter.get_absolute_url }}">{{ chapter.title }}</a></li>
                    {% endfor %}
                </ul>
              </div>
        </aside>
    </div>

{% endblock content %}

templates/book_list.html
{% extends 'base.html' %}

{% block breadcrumb %}
    <li class="breadcrumb-item active" aria-current="page">Book List</li>
{% endblock breadcrumb %}


{% block content %}

<h1>This is the book list</h1>
<hr>

{% for book in queryset %}
    <div class="card" style="width: 18rem;">
        <div class="card-body">
        <h5 class="card-title">{{ book.title }}</h5>
        <h6 class="card-subtitle mb-2 text-muted">{{ book.publication_date }}</h6>
        <p class="card-text">
            {% for author in book.authors.all %}
                <span>{{ author }}</span>
                {% if book.authors.count > 1 %} | {% endif %}
            {% endfor %}
        </p>
        <a class="card-link" href="{{ book.get_absolute_url }}">{{ book }}</a>
        </div>
    </div>
{% endfor %}

{% endblock content %}

templates/chapter_detail.html
{% extends 'base.html' %}

{% block breadcrumb %}
    <li class="breadcrumb-item" aria-current="page"><a href="{% url 'books:book-list' %}">Book List</a></li>
    <li class="breadcrumb-item" aria-current="page"><a href="{{ chapter.book.get_absolute_url }}">{{ chapter.book.title }}</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{ chapter.title }}</li>
{% endblock breadcrumb %}

{% block content %}
    <div class='row'>
        <main class='col-md-3 mx-auto'>
            <div class="card" style="width: 20rem;">
                <div class="card-header text-center">{{ chapter.book.title }}</div>
                <img src="{{ chapter.book.cover.url }}" class="card-img-top" alt="...">
                <div class="card-body">
                <p class="card-text">Published: {{ chapter.book.publication_date }}</p>
                </div>
            </div>
        </main>

        <aside class='col-md-4 mx-auto'>
            <div class="card" style="width: 18rem;">
                <div class="card-header">
                Exercises
                </div>
                <ul class="list-group list-group-flush">
                    {% for exercise in chapter.exercise_set.all %}
                        <li class="list-group-item">{{ exercise.exercise_number }}. <a href="{{ exercise.get_absolute_url }}">{{ exercise.title }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </aside>
    </div>

{% endblock content %}

templates/exercise_detail.html
{% extends 'base.html' %}
{% load static %}

{% block breadcrumb %}
    <li class="breadcrumb-item" aria-current="page"><a href="{% url 'books:book-list' %}">Book List</a></li>
    <li class="breadcrumb-item" aria-current="page"><a href="{{ exercise.chapter.book.get_absolute_url }}">{{ exercise.chapter.book.title }}</a></li>
    <li class="breadcrumb-item" aria-current="page"><a href="{{ exercise.chapter.get_absolute_url }}">{{ exercise.chapter.title }}</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{ exercise.title }}</li>
{% endblock breadcrumb %}

{% block content %}
    <div class='row'>
        <main class='col-md-4 mx-auto'>
            <div class="card" style="width: 20rem;">
                <div class="card-header text-center">{{ exercise.chapter.book.title }}</div>
                <img src="{{ exercise.chapter.book.cover.url }}" class="card-img-top" alt="...">
                <div class="card-body">
                <p class="card-text">Published: {{ exercise.chapter.book.publication_date }}</p>
                </div>
            </div>
        </main>

        <aside class='col mx-auto text-center'>
            <div class="card " style="width:100%;">
                <div class="card-header">
                Solutions
                </div>

                {% if exercise.chapter.book in request.user.userlibrary.book_list %}

                    <div class="accordion" id="accordionExample">
                        {% for solution in exercise.solution_set.all %}
                            <div class="accordion-item">
                            <h2 class="accordion-header" id="heading-{{ solution.solution_number }}">
                                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-{{ solution.solution_number }}" aria-expanded="true" aria-controls="collapse-{{ solution.solution_number }}">
                                    Solution {{ solution.solution_number }}
                                </button>
                            </h2>
                            <div id="collapse-{{ solution.solution_number }}" class="accordion-collapse collapse" aria-labelledby="heading-{{ solution.solution_number }}" data-bs-parent="#accordionExample">
                                <div class="accordion-body">
                                    <img src="{{ solution.image.url }}" class="card-img-top" alt="...">
                                </div>
                            </div>
                            </div>
                        {% endfor %}
                    </div>
                
                {% else %}
                    <h4 class="text-center px-4 py-2" style="letter-spacing: 1.5px;">You do  not have acces to this book. <a href="#">Please Purchase this book</a> to have access to the solutions</h4>
                    <img src="{% static 'images/lock.png' %}" alt="" class="mx-auto" style="width:30%;">
                {% endif %}

            </div>
        </aside>
    </div>


{% endblock content %}